// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Y8ADZL2V6bfsPIXRi8eQHgXd-uxSt_0',
    appId: '1:556366873927:web:5c722b886706d3c0317862',
    messagingSenderId: '556366873927',
    projectId: 'examenchat-2d228',
    authDomain: 'examenchat-2d228.firebaseapp.com',
    storageBucket: 'examenchat-2d228.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCluF4ZvZII7Il7TsgHPDRiHu5tyH04LQ8',
    appId: '1:556366873927:android:cea69e6a77161e5c317862',
    messagingSenderId: '556366873927',
    projectId: 'examenchat-2d228',
    storageBucket: 'examenchat-2d228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHIs8MAJ9cMusTeRVaVMqmt7lXg6_p1yk',
    appId: '1:556366873927:ios:d2a60f923964046f317862',
    messagingSenderId: '556366873927',
    projectId: 'examenchat-2d228',
    storageBucket: 'examenchat-2d228.appspot.com',
    iosBundleId: 'com.example.examenfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHIs8MAJ9cMusTeRVaVMqmt7lXg6_p1yk',
    appId: '1:556366873927:ios:d2a60f923964046f317862',
    messagingSenderId: '556366873927',
    projectId: 'examenchat-2d228',
    storageBucket: 'examenchat-2d228.appspot.com',
    iosBundleId: 'com.example.examenfi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Y8ADZL2V6bfsPIXRi8eQHgXd-uxSt_0',
    appId: '1:556366873927:web:05b45680783ba839317862',
    messagingSenderId: '556366873927',
    projectId: 'examenchat-2d228',
    authDomain: 'examenchat-2d228.firebaseapp.com',
    storageBucket: 'examenchat-2d228.appspot.com',
  );
}
